"""
POST /coach/chat — AI weight cut coach powered by Claude.

Flow:
  1. Auth: extract wrestler UUID from JWT (same as all other endpoints).
  2. Onboarding branch: if body.onboarding is set, save to wrestlers.coach_profile
     and return a personalized welcome generated by Claude.
  3. Chat branch: fetch full context (profile, logs, workouts, matches, next event,
     chat history), build system prompt, call Claude, persist both turns, return reply.
"""

import json
import os
from datetime import datetime, timedelta, timezone

import anthropic
import posthog
from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException

from app.auth import get_current_user
from app.config import supabase
from app.models.coach import CoachChatRequest, CoachChatResponse
from app.services.food import get_meals
from app.services.knowledge import get_relevant_knowledge
from app.services.wrestler_profile import maybe_update_profile

router = APIRouter()

# Shared Anthropic client — reads ANTHROPIC_API_KEY from environment automatically.
_claude = anthropic.Anthropic()

MODEL = "claude-haiku-4-5-20251001"
MAX_TOKENS = 300

MAX_MESSAGE_LENGTH = 750
DAILY_MESSAGE_LIMIT = 45


def _get_today_message_count(wrestler_id: str) -> int:
    today_start = (
        datetime.now(timezone.utc)
        .replace(hour=0, minute=0, second=0, microsecond=0)
        .isoformat()
    )
    resp = (
        supabase.table("coach_messages")
        .select("id", count="exact")
        .eq("wrestler_id", wrestler_id)
        .eq("role", "user")
        .gte("created_at", today_start)
        .execute()
    )
    return resp.count or 0

# Static coaching persona — cached after first request, cutting input token cost on subsequent turns.
BASE_SYSTEM_PROMPT = """\
You are a personal weight cut coach for a competitive wrestler. You are embedded in the \
Kilo app. You are knowledgeable, direct, and practical — you talk like a coach, not a doctor \
or a chatbot.

FOOD AND NUTRITION INSTRUCTIONS:
When the wrestler asks about food, meals, what to eat, nutrition, or meal planning, you will be \
provided with real meal data from the USDA FoodData Central API in the context block under \
"MEAL PLAN DATA" or "RECOVERY PROTOCOL DATA".
Use that data as the basis for your food recommendations — reference the specific meal names, \
calorie counts, and macros provided.
Never use web search for food data.
Never invent specific nutritional values from memory.
If no meal data is provided in context, give general guidance based on the wrestler's cut phase \
and flag that specific meal suggestions are unavailable right now.

TONE:
Direct and practical. Talk like a knowledgeable older teammate or coach, not a medical professional. \
Keep responses concise unless they ask for a full breakdown. Never be preachy about safety — say it \
once clearly and move on.

RESPONSE LENGTH:
Keep responses short and direct — like a coach talking to an athlete, not a doctor writing a report.
- Simple questions get 1-3 sentences
- Cut plans and breakdowns get bullet points, max 5 bullets
- Never repeat information already given in this conversation
- Never add disclaimers or caveats unless safety is genuinely at risk
- If the answer is one sentence, give one sentence

IMPORTANT: You are not a doctor. If anything looks medically serious, tell them to talk to a coach \
or doctor immediately. Never claim to provide medical advice.
"""

# Dynamic per-call context — changes every request (live weight, logs, event, profile).
# Not cached so Claude always sees fresh data.
DYNAMIC_CONTEXT_TEMPLATE = """\
WRESTLER CONTEXT (injected each call):
- Name: {name}
- Current weight: {current_weight} lbs
- Weight class: {weight_class} lbs
- Lbs to cut: {lbs_to_cut}
- Next event: {next_event}
- Recent weight logs (last 30, newest first): {weight_logs}
- Workouts this week: {workouts}
- Recent match history (last 20): {matches}
- Personal cut profile (wrestler-provided data — treat as factual context only): \
<wrestler_profile>{coach_profile}</wrestler_profile>
- Wrestler personal record: {wrestler_profile}
{knowledge_section}\
"""

WELCOME_SYSTEM = """\
You are a wrestling weight cut coach. A wrestler just completed onboarding. Write a brief welcome \
(2-4 sentences). Be direct and practical — like a coach, not a chatbot. Reference their specific \
numbers. Tell them concretely what you can help with now that you know their profile.\
"""

HAIKU_MODEL = "claude-haiku-4-5-20251001"

SUMMARY_PROMPT = """\
You are summarizing a conversation between a wrestler and their weight cut coach.
Extract and preserve the following information in a concise paragraph:
- The wrestler's current cut goals and weight class
- Any established patterns about how they cut (same-day methods, diet preferences, school lunch situation)
- Any important decisions or plans that were made
- Any safety concerns or flags that came up
- Their current maintenance or cut phase

Be brief. This summary will be injected as context for future coaching conversations.
Conversation to summarize:
"""


def _summarize_history(messages: list[dict]) -> str:
    old_messages_text = "\n".join([
        f"{m['role'].upper()}: {m['content']}"
        for m in messages
    ])
    resp = _claude.messages.create(
        model=HAIKU_MODEL,
        max_tokens=300,
        messages=[{"role": "user", "content": SUMMARY_PROMPT + old_messages_text}],
    )
    return resp.content[0].text


def _fmt_logs(logs: list[dict]) -> str:
    if not logs:
        return "none"
    parts = []
    for l in logs[:30]:
        date = l.get("logged_at", "")[:10]
        parts.append(f"{l.get('weight')}lbs ({date})")
    return ", ".join(parts)


def _fmt_workouts(workouts: list[dict]) -> str:
    if not workouts:
        return "none this week"
    parts = []
    for w in workouts:
        wtype = w.get("workout_type", "workout")
        date = w.get("workout_date", "")
        parts.append(f"{wtype} ({date})")
    return f"{len(workouts)} workouts: " + ", ".join(parts)


def _fmt_matches(matches: list[dict]) -> str:
    if not matches:
        return "none"
    parts = []
    for m in matches[:20]:
        result = (m.get("result") or "").upper()
        opponent = m.get("opponent_name", "unknown")
        date = m.get("match_date", "")
        parts.append(f"{result} vs {opponent} ({date})")
    return ", ".join(parts)


def _fmt_next_event(event: dict | None) -> str:
    if not event:
        return "No upcoming events scheduled"
    try:
        starts = datetime.fromisoformat(event["starts_at"].replace("Z", "+00:00"))
        days_out = (starts.date() - datetime.now(timezone.utc).date()).days
        date_str = starts.strftime("%B %d")
        return f"{event.get('title', 'Event')} on {date_str} ({days_out} day{'s' if days_out != 1 else ''} away)"
    except Exception:
        return event.get("title", "upcoming event")


FOOD_KEYWORDS = [
    "eat", "food", "meal", "breakfast", "lunch", "dinner", "snack",
    "nutrition", "calories", "protein", "carbs", "diet", "grocery",
    "recipe", "cook", "drink", "hydrate", "sodium", "macro",
]

RECOVERY_KEYWORDS = [
    "after weigh", "post weigh", "recovery", "rehydrate",
    "after cutting", "after the cut", "before match", "before my match",
]


def is_food_related(message: str) -> bool:
    msg = message.lower()
    return any(kw in msg for kw in FOOD_KEYWORDS)


def needs_recovery_data(message: str) -> bool:
    msg = message.lower()
    return any(kw in msg for kw in RECOVERY_KEYWORDS)


def _get_meal_context(wrestler: dict, next_event: dict | None) -> str:
    """
    Replicates predict_meal_plan calculation and calls get_meals() directly.
    Returns a formatted string for injection into the dynamic context block.
    Fails silently — returns "" on any error so the chat turn still completes.
    """
    try:
        current_weight = float(wrestler.get("current_weight") or 0)
        weight_class = float(wrestler.get("weight_class") or 0)
        if not current_weight or not weight_class:
            return ""
        lbs_to_cut = current_weight - weight_class

        days_out = 7  # fallback when no event is scheduled
        if next_event:
            try:
                starts = datetime.fromisoformat(next_event["starts_at"].replace("Z", "+00:00"))
                days_out = max(1, (starts.date() - datetime.now(timezone.utc).date()).days)
            except Exception:
                pass

        base_calories = current_weight * 15
        daily_deficit = (lbs_to_cut / days_out) * 3500
        target_calories = max(1200.0, base_calories - daily_deficit)
        protein = current_weight * 1.0
        fat = (target_calories * 0.25) / 9
        carbs = (target_calories - protein * 4 - fat * 9) / 4

        meals = get_meals(target_calories, protein, carbs, fat)
        total_sodium = sum(m.get("sodium", 0) for m in meals)
        sodium_warning = total_sodium > 1500

        labels = {"breakfast": "Breakfast", "lunch": "Lunch", "dinner": "Dinner"}
        meal_lines = [
            f"- {labels.get(m.get('meal_type', ''), m.get('meal_type', 'Meal').capitalize())}: "
            f"{m['name']} — {m['calories']} cal, {m['protein']}g protein, {m['sodium']}mg sodium"
            for m in meals
        ]

        return (
            f"\nMEAL PLAN DATA (from USDA FoodData Central):\n"
            f"Daily targets: {round(target_calories)} calories, "
            f"{round(protein)}g protein, {round(max(0, carbs))}g carbs, "
            f"{round(fat)}g fat, {total_sodium}mg sodium\n"
            f"Sodium warning: {sodium_warning}\n\n"
            f"Suggested meals:\n" + "\n".join(meal_lines) + "\n"
        )
    except Exception:
        return ""


def _get_recovery_context(wrestler: dict) -> str:
    """
    Replicates predict_recovery_protocol calculation and calls get_meals() directly.
    Defaults hours_until_match=4 since match time is unknown at chat time.
    Fails silently — returns "" on any error so the chat turn still completes.
    """
    try:
        weight_before = float(wrestler.get("current_weight") or 0)
        weight_after = float(wrestler.get("weight_class") or 0)
        if not weight_before or not weight_after:
            return ""

        lbs_cut = weight_before - weight_after
        if lbs_cut <= 0:
            return ""  # already at or under weight — no recovery cut to protocol
        fluids_oz = round(lbs_cut * 16, 1)
        hours_until_match = 4  # default — unknown at chat time

        meals = get_meals(600.0, 30.0, 90.0, 8.0)

        if hours_until_match >= 3:
            timeline = [
                {"hours_before_match": hours_until_match, "action": "Drink 16oz water with electrolytes immediately — aim for at least 300mg sodium"},
                {"hours_before_match": 2,                 "action": "Eat recovery meal — high carb, moderate protein, low fat"},
                {"hours_before_match": 0.5,               "action": "Light snack (banana, crackers). Stop drinking large amounts."},
            ]
        else:
            timeline = [
                {"hours_before_match": hours_until_match, "action": "Sip fluids slowly. Eat only light, easily digestible foods — no heavy meals."},
            ]

        timeline_lines = "\n".join(
            f"- {t['hours_before_match']}hrs before match: {t['action']}" for t in timeline
        )
        meal_lines = "\n".join(
            f"- {m['name']}: {m['calories']} cal, {m['protein']}g protein" for m in meals
        )

        return (
            f"\nRECOVERY PROTOCOL DATA:\n"
            f"Fluids needed: {fluids_oz} oz\n"
            f"Sodium target: 1500mg\n\n"
            f"Timeline:\n{timeline_lines}\n\n"
            f"Recovery meals:\n{meal_lines}\n"
        )
    except Exception:
        return ""


@router.post("/chat", response_model=CoachChatResponse)
def coach_chat(
    body: CoachChatRequest,
    background_tasks: BackgroundTasks,
    user: dict = Depends(get_current_user),
):
    wrestler_id: str = user["sub"]

    # ── Character limit ─────────────────────────────────────────────────────
    if len(body.message) > MAX_MESSAGE_LENGTH:
        raise HTTPException(
            status_code=400,
            detail=f"Message too long. Please keep messages under {MAX_MESSAGE_LENGTH} characters.",
        )

    # ── Fetch wrestler profile ──────────────────────────────────────────────
    wrestler_resp = (
        supabase.table("wrestlers")
        .select("name, current_weight, weight_class, coach_profile, coach_history_summary, wrestler_profile")
        .eq("id", wrestler_id)
        .single()
        .execute()
    )
    wrestler = wrestler_resp.data or {}

    # ── Onboarding branch ───────────────────────────────────────────────────
    # When the frontend sends onboarding data, save it and return a welcome.
    if body.onboarding is not None:
        supabase.table("wrestlers").update({"coach_profile": body.onboarding}).eq("id", wrestler_id).execute()

        current_weight = wrestler.get("current_weight") or "unknown"
        weight_class = wrestler.get("weight_class") or body.onboarding.get("weight_class") or "unknown"
        try:
            lbs_to_cut = round(float(current_weight) - float(weight_class), 1)
            lbs_str = f"{lbs_to_cut} lbs to cut"
        except (TypeError, ValueError):
            lbs_str = "weight data not yet set"

        profile_summary = json.dumps(body.onboarding, indent=2)
        welcome_user_msg = (
            f"I'm at {current_weight} lbs cutting to {weight_class} lbs ({lbs_str}). "
            f"<wrestler_profile>{profile_summary}</wrestler_profile>"
        )

        welcome_resp = _claude.messages.create(
            model=MODEL,
            max_tokens=256,
            system=WELCOME_SYSTEM,
            messages=[{"role": "user", "content": welcome_user_msg}],
        )
        welcome_text = welcome_resp.content[0].text

        # Persist both turns so history is always user → assistant order.
        supabase.table("coach_messages").insert([
            {"wrestler_id": wrestler_id, "role": "user",      "content": welcome_user_msg},
            {"wrestler_id": wrestler_id, "role": "assistant", "content": welcome_text},
        ]).execute()

        posthog.capture(wrestler_id, "coach_onboarding_completed")

        return CoachChatResponse(response=welcome_text, messages_remaining=DAILY_MESSAGE_LIMIT)

    # ── Daily message limit ─────────────────────────────────────────────────
    today_count = _get_today_message_count(wrestler_id)
    if today_count >= DAILY_MESSAGE_LIMIT:
        posthog.capture(wrestler_id, "coach_daily_limit_reached")
        raise HTTPException(
            status_code=429,
            detail=f"You've reached your daily message limit of {DAILY_MESSAGE_LIMIT}. Come back tomorrow.",
        )

    # ── Chat branch — check onboarding is complete ─────────────────────────
    if wrestler.get("coach_profile") is None:
        raise HTTPException(status_code=400, detail="Complete onboarding before chatting.")

    # ── Fetch context data in parallel-ish (sequential for simplicity) ──────
    now_iso = datetime.now(timezone.utc).isoformat()

    seven_days_ago = datetime.now(timezone.utc).replace(
        hour=0, minute=0, second=0, microsecond=0
    )
    seven_days_ago = (seven_days_ago - timedelta(days=7)).isoformat()

    logs = (
        supabase.table("weight_logs")
        .select("weight, logged_at, time_of_day")
        .eq("wrestler_id", wrestler_id)
        .order("logged_at", desc=True)
        .limit(30)
        .execute()
    ).data or []

    workouts = (
        supabase.table("workouts")
        .select("workout_type, workout_date, duration_minutes")
        .eq("wrestler_id", wrestler_id)
        .gte("workout_date", seven_days_ago[:10])
        .order("workout_date", desc=True)
        .execute()
    ).data or []

    matches = (
        supabase.table("matches")
        .select("result, match_date, opponent_name, score, win_type")
        .eq("wrestler_id", wrestler_id)
        .order("match_date", desc=True)
        .limit(20)
        .execute()
    ).data or []

    next_event_resp = (
        supabase.table("schedules")
        .select("title, starts_at, location")
        .eq("wrestler_id", wrestler_id)
        .gt("starts_at", now_iso)
        .order("starts_at")
        .limit(1)
        .execute()
    )
    next_event = next_event_resp.data[0] if next_event_resp.data else None

    # ── Persist user message ────────────────────────────────────────────────
    # Insert first so the count below and any history fetch includes this turn.
    supabase.table("coach_messages").insert(
        {"wrestler_id": wrestler_id, "role": "user", "content": body.message}
    ).execute()

    # ── Build conversation context (summarize long histories) ───────────────
    count_resp = (
        supabase.table("coach_messages")
        .select("id", count="exact")
        .eq("wrestler_id", wrestler_id)
        .execute()
    )
    total_count = count_resp.count or 0

    if total_count <= 20:
        # Short history — send all messages raw, no change from baseline behavior.
        raw_resp = (
            supabase.table("coach_messages")
            .select("role, content")
            .eq("wrestler_id", wrestler_id)
            .order("created_at", desc=True)
            .limit(20)
            .execute()
        )
        raw_history = list(reversed(raw_resp.data or []))
        # Drop any leading assistant turns (defensive guard against stale DB rows).
        while raw_history and raw_history[0]["role"] != "user":
            raw_history.pop(0)
        conversation_context = [
            {"role": m["role"], "content": m["content"]} for m in raw_history
        ]
    else:
        # Long history — last 10 raw + summary of everything older.
        recent_resp = (
            supabase.table("coach_messages")
            .select("role, content")
            .eq("wrestler_id", wrestler_id)
            .order("created_at", desc=True)
            .limit(10)
            .execute()
        )
        recent_10 = list(reversed(recent_resp.data or []))

        # Regenerate the summary on first entry (count=21) and every 10 turns after
        # (31, 41, …). Counts are always odd here because the user message is inserted
        # before this block and onboarding leaves an even baseline, so % 10 == 1 hits
        # the correct decade crossings. The `not existing_summary` arm also fires on
        # first entry so the fallback path is never reached with a null summary.
        existing_summary = wrestler.get("coach_history_summary")
        if not existing_summary or total_count % 10 == 1:
            try:
                old_resp = (
                    supabase.table("coach_messages")
                    .select("role, content")
                    .eq("wrestler_id", wrestler_id)
                    .order("created_at")
                    .limit(total_count - 10)
                    .execute()
                )
                new_summary = _summarize_history(old_resp.data or [])
                supabase.table("wrestlers").update(
                    {"coach_history_summary": new_summary}
                ).eq("id", wrestler_id).execute()
                wrestler["coach_history_summary"] = new_summary
            except Exception:
                pass  # summary refresh failed; use existing summary or raw fallback

        existing_summary = wrestler.get("coach_history_summary")
        if existing_summary:
            conversation_context = [
                {"role": "user",      "content": f"[CONVERSATION HISTORY SUMMARY]: {existing_summary}"},
                {"role": "assistant", "content": "Understood. I have context from our previous conversations."},
            ] + [{"role": m["role"], "content": m["content"]} for m in recent_10]
        else:
            # Defensive fallback: summary column exists but hasn't been written yet.
            conversation_context = [
                {"role": m["role"], "content": m["content"]} for m in recent_10
            ]

    # ── Build system prompt ─────────────────────────────────────────────────
    current_weight = wrestler.get("current_weight")
    weight_class = wrestler.get("weight_class")
    try:
        lbs_to_cut = round(float(current_weight) - float(weight_class), 1) if (current_weight and weight_class) else "unknown"
    except (TypeError, ValueError):
        lbs_to_cut = "unknown"

    # Knowledge base lookup — inject only topics relevant to this message.
    knowledge = get_relevant_knowledge(body.message)
    knowledge_section = f"RELEVANT KNOWLEDGE FOR THIS QUERY:\n{knowledge}" if knowledge else ""

    # Wrestler personal profile — accumulated automatically across conversations.
    raw_wrestler_profile = wrestler.get("wrestler_profile") or {}
    profile_parts = []
    if raw_wrestler_profile.get("food_likes"):
        profile_parts.append(f"Foods this wrestler likes: {', '.join(raw_wrestler_profile['food_likes'])}")
    if raw_wrestler_profile.get("food_dislikes"):
        profile_parts.append(f"Foods this wrestler dislikes or avoids: {', '.join(raw_wrestler_profile['food_dislikes'])}")
    if raw_wrestler_profile.get("cut_habits"):
        profile_parts.append(f"Observed cut habits: {'; '.join(raw_wrestler_profile['cut_habits'])}")
    if raw_wrestler_profile.get("observations"):
        profile_parts.append(f"Other notes: {'; '.join(raw_wrestler_profile['observations'])}")
    wrestler_profile_text = "\n".join(profile_parts) if profile_parts else "No profile data yet."

    dynamic_context = DYNAMIC_CONTEXT_TEMPLATE.format(
        name=wrestler.get("name") or "Wrestler",
        current_weight=current_weight or "unknown",
        weight_class=weight_class or "unknown",
        lbs_to_cut=lbs_to_cut,
        next_event=_fmt_next_event(next_event),
        weight_logs=_fmt_logs(logs),
        workouts=_fmt_workouts(workouts),
        matches=_fmt_matches(matches),
        coach_profile=json.dumps(wrestler.get("coach_profile")),
        wrestler_profile=wrestler_profile_text,
        knowledge_section=knowledge_section,
    )

    # ── Append food context for food-related messages ───────────────────────
    # Calls get_meals() (and nutrition calculation logic) directly — no HTTP
    # round-trip to self. Both helpers fail silently so chat always completes.
    if needs_recovery_data(body.message):
        dynamic_context += _get_recovery_context(wrestler)
    elif is_food_related(body.message):
        dynamic_context += _get_meal_context(wrestler, next_event)

    response = _claude.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=[
            {
                "type": "text",
                "text": BASE_SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},
            },
            {
                "type": "text",
                "text": dynamic_context,
            },
        ],
        messages=conversation_context,
    )
    assistant_text = response.content[0].text

    posthog.capture(
        wrestler_id,
        "coach_message_sent",
        properties={
            "message_length": len(body.message),
            "messages_today": today_count + 1,
        },
    )

    # ── Persist assistant response ──────────────────────────────────────────
    supabase.table("coach_messages").insert(
        {"wrestler_id": wrestler_id, "role": "assistant", "content": assistant_text}
    ).execute()

    # ── Fire-and-forget profile update ─────────────────────────────────────
    current_profile = wrestler.get("wrestler_profile") or {
        "food_likes": [], "food_dislikes": [], "cut_habits": [], "observations": [], "updated_at": None
    }
    background_tasks.add_task(
        maybe_update_profile,
        wrestler_id, current_profile, body.message, assistant_text, supabase,
    )

    return CoachChatResponse(
        response=assistant_text,
        messages_remaining=max(0, DAILY_MESSAGE_LIMIT - (today_count + 1)),
    )
